static_dir = "./static/"
log_dir = "/home/vaclav/unmute/logs"
instance_name = "tts"
authorized_ids = ["public_token"]

[modules.tts_py]
type = "Py"
path = "/api/tts_streaming"
text_tokenizer_file = "hf://kyutai/unmute/test_en_fr_audio_8000.model"
batch_size = 2
text_bos_token = 1

[modules.tts_py.py]
log_folder = "/logs"
moshi_weight = "hf://kyutai/unmute/moshi_1e68beda_240/checkpoint.safetensors"
config_path = "hf://kyutai/unmute/moshi_1e68beda_240/config.json"
voice_folder = "hf-snapshot://kyutai/unmute-voices/unmute-prod-website/*.safetensors"
default_voice = "unmute-prod-website/barack_demo.wav"
cfg_coef = 1
cfg_condition = 2.0
n_q = 24
