static_dir = "./static/"
log_dir = "/logs"
instance_name = "tts"
authorized_ids = ["public_token"]

[modules.tts_py]
type = "Py"
path = "/api/tts_streaming"
# This is the only way currently to get the python file.
script = "/root/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/moshi-server-0.6.0/tts.py"
text_tokenizer_file = "/models/test_en_fr_audio_8000.model"
batch_size = 16
text_bos_token = 1

[modules.tts_py.py]
log_folder = "/logs"
moshi_weight = "/models/moshi/moshi_1e68beda_240/checkpoint.safetensors"
config_path = "/models/moshi/moshi_1e68beda_240/config.json"
tokenizer = "/models/test_en_fr_audio_8000.model"
voice_folder = "/models/tts-voices/"
default_voice = "barack_demo.wav"
cfg_coef = 1
cfg_condition = 2.0
n_q = 24
