name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build all docker images
        run: docker buildx bake --progress=plain -f swarm-deploy.yml
        env:
          DOMAIN: hello 
