name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-docker-images:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build all docker images
        run: docker buildx bake --progress=plain -f swarm-deploy.yml
        env:
          DOMAIN: hello
  pre-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.7.12"

      - name